version: '3'

services:
  api:
    build:
      context: ./api
    ports:
      - 3003:3003
    depends_on:
      - db
    command: bin/run
    volumes:
      - ./api:/app

  client:
    build:
      context: ./client
    ports:
      - 4200:4200
    environment:
      - GITHUB_ACTIONS=${GITHUB_ACTIONS}
    command: bin/run
    volumes:
      - ./client:/app

  db:
    image: mongo:latest
    ports:
      - 27017:27017
    volumes:
      - dbdata:/var/lib/mongodb/data

volumes:
  dbdata:
