name: Deployment
on:
  push:
    branches:
      - master
      - acceptance
jobs:
  api:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Build Docker images
        run: docker-compose build api
      - name: Install Node packages
        run: docker-compose run --rm api npm install
    # - name: Unit tests
    #   run: docker-compose run --rm api bin/coverage
    # - name: Formatting
    #   run: docker-compose run --rm api bin/format
    # - name: Credo
    #   run: docker-compose run --rm api bin/credo
    # - name: Security
    #   run: docker-compose run --rm api bin/security
  client:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Build Docker images
        run: docker-compose build client
      - name: Install Node packages
        run: docker-compose run --rm client npm install
      # - name: Unit tests
      #   run: docker-compose run --rm client bin/jest
      # - name: TSLint
      #   run: docker-compose run --rm client bin/tslint
      # - name: Stylelint
      #   run: docker-compose run --rm client bin/stylelint

  publish:
    needs: [api, client]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Build Docker image and publish to registry
        uses: elgohr/Publish-Docker-Github-Action@master
        with:
          name: s1mpler/fake-team-website-production
          dockerfile: prod.Dockerfile
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
